config/routes.rb
Rails.application.routes.draw do
  root 'properties#new'
  resources :properties do
    member do
      get 'customers/new'
    end
    member do
      get 'ranking'
    end
  resources :consultation_details
  end

  get 'consultation_matters/index'
  get 'consultation_matters/new'
  get 'consultation_matters/show'

  resources :customers
  resources :specialists
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/specialist.rb
class Specialist < ApplicationRecord

  has_many :contacts
  extend OrderAsSpecified
end

app/controllers/specialists_controller.rb
class SpecialistsController < ApplicationController
  def index
    @specialists = Specialist.all
  end

  def show
    @specialist = Specialist.find(params[:id])
    # @customer = Customer.new
    # render template: "customers/new"
  end
end

app/views/specialists/index.html.erb
<h1>Specialists#index</h1>
<p>Find me in app/views/specialists/index.html.erb</p>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @specialists.each do |specialist| %>
      <tr>
        <td><%= specialist.name %></td>
        <td><%= specialist.expertise_property %></td>
        <td><%= specialist.consultation_item %></td>
        <td><%= specialist.qualification %></td>
        <td><%= specialist.description %></td>
        <td><%= specialist.career %></td>
        <td><%= specialist.icon %></td>
        <td><%= specialist.string %></td>
        <td><%= link_to '詳細', specialist_path(specialist.id) %></td>
     </tr>
    <% end %>
  </tbody>
</table>

app/views/specialists/show.html.erb
<h1>Specialists#show</h1>
<p>Find me in app/views/specialists/show.html.erb</p>

<div class="specialist">
  <%= @specialist.name %>
  <%= @specialist.expertise_property %>
  <%= @specialist.consultation_item %>
  <%= @specialist.qualification %>
  <%= @specialist.description %>
  <%= @specialist.career %>
  <%= @specialist.icon %>
  <%= @specialist.icon %>
  <%= @specialist.id %>
</div>


<h3>専門家に相談するためお客様情報をご記入ください</h3>
<%= render partial: "customers/form" %>
<h3>相談したい内容をご記入ください</h3>
<%= render partial: "consultation_matters/form" %>
<%= render partial: "consultation_details/form" %>