config/routes.rb
Rails.application.routes.draw do
  root 'properties#new'
  resources :properties do
    member do
      get 'customers/new'
    end
    member do
      get 'ranking'
    end
  resources :consultation_details
  end

  get 'consultation_matters/index'
  get 'consultation_matters/new'
  get 'consultation_matters/show'

  resources :customers
  resources :specialists
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/property.rb
class Property < ApplicationRecord
    belongs_to :customer, optional: true

    extend ActiveHash::Associations::ActiveRecordExtensions
    belongs_to :prefecture

    has_many :consultation_details, dependent: :destroy
    accepts_nested_attributes_for :consultation_details, reject_if: lambda {|attributes| attributes['content'].blank?}
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_action :set_property, only: %i[ show destroy ranking ]

  def index
    @properties = Property.all
  end

  def ranking
    # Calculate scores from specialists and property information.
    @property_scores = Property.where(id: params[:id]).pluck(:newly_built_house, :used_house, :newly_built_condominium, :used_condominium )
    @property_scores = @property_scores.flatten
    @specialist_scores = Specialist.pluck(:newly_built_house, :used_house, :newly_built_condominium, :used_condominium )
    @specialist_scores = @specialist_scores.map{|n| [n, @property_scores].transpose.map{|m| m.inject(:*)}}
    @specialist_scores = @specialist_scores.map(&:sum)
    @specialist_ids = Specialist.pluck(:id)
    @ary = [@specialist_ids, @specialist_scores].transpose
    @new_scores = Hash[*@ary.flatten].sort_by { |_, v| v }.reverse.to_h
    @new_specialist_ids = @new_scores.keys.first(5)
    @best_specialists = Specialist.order_as_specified(id: @new_specialist_ids).first(5)
  end

  def new
    @property = Property.new
    @property.consultation_details.build
    # 6.times { @property.consultation_details.build }
    # @consultation_detail = ConsultationDetail.new
    # @consultation_matters = ConsultationMatter.all
    # @consultation_detail = ConsultationDetail.all
  end

  def create
    @property = Property.new(property_params)

    respond_to do |format|
      if @property.save
        # format.html { redirect_to controller: :properties, action: :ranking, id: @property.id, notice: "Property was successfully created." }
        # format.html { redirect_to "/customers/new", notice: "Property was successfully created." }
        format.html { redirect_to controller: :customers, action: :new, id: @property.id, notice: "Property was successfully created." }
        format.json { render :new, status: :created, location: @property }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
  end

  private
  def set_property
    @property = Property.find(params[:id])
  end

  def property_params
    params.require(:property).permit(
      :property_type,
      :newly_built_house,
      :used_house,
      :newly_built_condominium,
      :used_condominium,
      :land,
      :price_and_pepayment,
      :building_and_structure,
      :floor_plan,
      :surrounding_environment,
      :family_relatives,
      :other_point,
      :other,
      :trader,
      :price,
      :prefecture_id,
      consultation_details_attributes: [:content],
      :property_choice[]
    )
  end
end

app/views/properties/_form.html.erb
<%= form_with(model: property, local: true) do |form| %>
<%#= form_with(model: [property, consultation_detail], local: true) do |form| %>

  <% if property.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(property.errors.count, "error") %> prohibited this property from being saved:</h2>

      <ul>
      <% property.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="green">
    <h2>相談内容を入力すると候補の専門家が見つかります</h2>
  </div>

  <h3>Ｑ、購入の決断に迷っている物件情報を入力してください</h3>

    <div class="field">
      <%= form.label :検討物件, class: "label" do %>
      <div class="property">

        <%= form.label :物件種類, class: "label" %>
        <div class="type_group">
          <div class="type">
            <%= form.radio_button :property_choice, {} %>
            <%= form.label :newly_built_house, "新築戸建" %>
          </div>

          <div class="type">
            <%= form.radio_button :property_choice, {} %>
            <%= form.label :used_house, "中古戸建" %>
          </div>

          <div class="type">
            <%= form.radio_button :property_choice, {} %>
            <%= form.label :newly_built_condominium, "新築マンション" %>
          </div>

          <div class="type">
            <%= form.radio_button :property_choice, {} %>
            <%= form.label :used_condominium, "中古マンション" %>
          </div>

          <div class="type">
            <%= form.radio_button :property_choice, {} %>
            <%= form.label :land, "土地のみ" %>
          </div>
        </div>

        <div class="field">
          <%= form.label :都道府県, class: "label" %>
          <%= form.collection_select(:prefecture_id, Prefecture.all, :id, :name,{include_blank: "選択してください"}, class: "input" ) %>
        </div>

        <div class="field">
          <%= form.label :物件URL, class: "label" %>
          <%= form.url_field :url, class: "input", placeholder:"https://◯◯◯◯" %>
        </div>

        <div class="field">
          <%= form.label :物件名, class: "label" %>
          <%= form.text_field :name, class: "input", placeholder:"スカイレジデンス名古屋" %>
        </div>

        <div class="field">
          <%= form.label :その他, class: "label" %>
          <%= form.text_field :other, class: "input", placeholder:"◯◯号" %>
        </div>
      </div>
      <% end %>
    </div>

    <div class="field">
      <%= form.label :取扱会社, class: "label" %>
      <%= form.text_field :trader, class: "input", placeholder:"株式会社◯◯◯◯" %>
    </div>

    <div class="field">
      <%= form.label :販売価格（業者からの提案価格）, class: "label" %>
      <%= form.text_field :price, class: "input", placeholder:"◯◯◯万円" %>
    </div>


  <h3>Ｑ、購入を決断する上で相談したいことはなんですか？（複数選択可）</h3>
  <div class="field">
    <%= form.check_box :price_and_pepayment, {},checked_value='1', unchecked_value='0' %>
    <%= form.label :価格・返済 %>
    <%#= render partial: "consultation_details/form" %>
    <%= form.fields_for :consultation_details do |f| %>
      <div class="content">
        <%= f.label :相談したい内容をなるべく具体的に記載ください %>
        <%= f.text_area :content, class: "text" %>
      </div>
    <% end %>
  </div>

  <div class="field">
    <%= form.check_box :building_and_structure, {},checked_value='1', unchecked_value='0' %>
    <%= form.label :建物・構造, class: "label" %>
    <%#= render partial: "consultation_details/form" %>
    <%= form.fields_for :consultation_details do |f| %>
      <div class="content">
        <%= f.label :相談したい内容をなるべく具体的に記載ください %>
        <%= f.text_area :content, class: "text" %>
      </div>
    <% end %>
  </div>

  <div class="field">
    <%= form.check_box :floor_plan, {},checked_value='1', unchecked_value='0' %>
    <%= form.label :間取り, class: "label" %>
    <%#= render partial: "consultation_details/form" %>
    <%= form.fields_for :consultation_details do |f| %>
      <div class="content">
        <%= f.label :相談したい内容をなるべく具体的に記載ください %>
        <%= f.text_area :content, class: "text" %>
      </div>
    <% end %>
  </div>

  <div class="field">
    <%= form.check_box :surrounding_environment, {},checked_value='1', unchecked_value='0' %>
    <%= form.label :周辺環境, class: "label" %>
    <%#= render partial: "consultation_details/form" %>
    <%= form.fields_for :consultation_details do |f| %>
      <div class="content">
        <%= f.label :相談したい内容をなるべく具体的に記載ください %>
        <%= f.text_area :content, class: "text" %>
      </div>
    <% end %>
  </div>

  <div class="field">
    <%= form.check_box :family_relatives, {},checked_value='1', unchecked_value='0' %>
    <%= form.label :家族・親族, class: "label" %>
    <%#= render partial: "consultation_details/form" %>
    <%= form.fields_for :consultation_details do |f| %>
      <div class="content">
        <%= f.label :相談したい内容をなるべく具体的に記載ください %>
        <%= f.text_area :content, class: "text" %>
      </div>
    <% end %>
  </div>

  <div class="field">
    <%= form.check_box :other_point, {},checked_value='1', unchecked_value='0' %>
    <%= form.label :その他の点, class: "label" %>
    <%#= render partial: "consultation_details/form" %>
    <%= form.fields_for :consultation_details do |f| %>
      <div class="content">
        <%= f.label :相談したい内容をなるべく具体的に記載ください %>
        <%= f.text_area :content, class: "text" %>
      </div>
    <% end %>
  </div>

<div class="btn">
  <%= form.submit "専門家を探す", class: "next" %>
</div>
<% end %>

app/views/properties/index.html.erb
<%# provide(:title, t('view.properties.show.title')) %>

<table>
  <thead>
    <tr>
      <th>新築戸建</th>
      <th>中古戸建</th>
      <th>新築マンション</th>
      <th>中古マンション</th>
      <th>土地のみ</th>
      <th>都道府県</th>
      <th>物件URL</th>
      <th>物件名</th>
      <th>その他</th>
      <th>取扱会社</th>
      <th>販売価格</th>
      <th>価格・返済</th>
      <th>建物・構造</th>
      <th>間取り</th>
      <th>周辺環境</th>
      <th>家族・親族</th>
      <th>その他の点</th>
    </tr>
  </thead>

  <tbody>
    <% @properties.each do |property| %>
      <tr>
        <td><%= property.newly_built_house %></td>
        <td><%= property.used_house %></td>
        <td><%= property.newly_built_condominium %></td>
        <td><%= property.used_condominium %></td>
        <td><%= property.land %></td>
        <td><%= property.prefecture_id %></td>
        <td><%= property.url %></td>
        <td><%= property.name %></td>
        <td><%= property.other %></td>
        <td><%= property.trader %></td>
        <td><%= property.price %></td>
        <td><%= property.price_and_pepayment %></td>
        <td><%= property.building_and_structure %></td>
        <td><%= property.floor_plan %></td>
        <td><%= property.surrounding_environment %></td>
        <td><%= property.family_relatives %></td>
        <td><%= property.other_point %></td>
        <td><%= link_to '詳細', property_path(property.id) %></td>
     </tr>
    <% end %>
  </tbody>
</table>

app/views/properties/new.html.erb
<%#= render 'form', property: @property %>
<%= render 'form', {property: @property, consultation_details: @consultation_details} %>

app/views/properties/ranking.erb
<h1>Properties#ranking</h1>
<%= @property.id %><br>
<%= p @new_scores %><br>
<%= p @new_specialist_ids %><br>

  <div class="green">
  <h3>オススメの専門家が5名見つかりました</h3>
  </div>

  <div class="specialist">
  <% @best_specialists.each do |specialist| %>
    <div class="chunk">
      <div class="icon"><p>アイコン</p><%= specialist.icon %></div>

      <div class="short">
        <div class="field">
          <p>氏名</p><%= specialist.name %>
        </div>

        <div class="field">
          <p>得意な物件</p><%= specialist.expertise_property %>
        </div>

        <div class="field">
          <p>相談可能項目</p><%= specialist.consultation_item %>
        </div>

        <div class="field">
          <p>資格</p><%= specialist.qualification %>
        </div>
      </div>

      <div class="long">
        <div class="field">
          <p>自己紹介</p><%= specialist.description %>
        </div>

        <div class="field">
          <p>経歴</p><%= specialist.career %>
        </div>
      </div>

      <div class="btn">
        <%# <%= form.radio_button :specialist_id, specialist.id %> %>
        <%= specialist.id %>
        <%= link_to '相談を申し込む', class: "next" %>
      </div>
    </div>
  <% end %>

app/views/properties/show.html.erb
<h1>Properties#show</h1>
<p>Find me in app/views/properties/show.html.erb</p>

<table>
  <tr>
    <th>新築戸建</th>
    <td><%= @property.newly_built_house %></td>
  </tr>
  <tr>
    <th>中古戸建</th>
    <td><%= @property.used_house %></td>
  </tr>
  <tr>
    <th>新築マンション</th>
    <td><%= @property.newly_built_condominium %></td>
  </tr>
  <tr>
    <th>中古マンション</th>
    <td><%= @property.used_condominium %></td>
  </tr>
  <tr>
    <th>土地のみ</th>
    <td><%= @property.land %></td>
  </tr>
  <tr>
    <th>都道府県</th>
    <td><%= @property.prefecture_id %></td>
  </tr>
  <tr>
    <th>物件URL</th>
    <td><%= @property.url %></td>
  </tr>
  <tr>
    <th>物件名</th>
    <td><%= @property.name %></td>
  </tr>
  <tr>
    <th>その他</th>
    <td><%= @property.other %></td>
  </tr>
  <tr>
    <th>取扱会社</th>
    <td><%= @property.trader %></td>
  </tr>
  <tr>
    <th>販売価格</th>
    <td><%= @property.price %></td>
  </tr>
  <tr>
    <th>価格・返済</th>
    <td><%= @property.price_and_pepayment %></td>
    <td><%#= @property.consultation_detail.content %></td>
  </tr>
  <tr>
    <th>建物・構造</th>
    <td><%= @property.building_and_structure %></td>
  </tr>
  <tr>
    <th>間取り</th>
    <td><%= @property.floor_plan %></td>
  </tr>
  <tr>
    <th>周辺環境</th>
    <td><%= @property.surrounding_environment %></td>
  </tr>
  <tr>
    <th>家族・親族</th>
    <td><%= @property.family_relatives %></td>
  </tr>
  <tr>
    <th>その他の点</th>
    <td><%= @property.other_point %></td>
  </tr>
  <tr>
    <th>顧客ID</th>
    <td><%= @property.customer_id %></td>
  </tr>
</table>