config/routes.rb
Rails.application.routes.draw do
  root 'properties#new'
  resources :properties do
    member do
      get 'customers/new'
    end
    member do
      get 'ranking'
    end
  resources :consultation_details
  end

  get 'consultation_matters/index'
  get 'consultation_matters/new'
  get 'consultation_matters/show'

  resources :customers
  resources :specialists
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/customer.rb
class Customer < ApplicationRecord
    has_many :properties
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: %i[ show destroy ]
  before_action :set_property, only: %i[ create ]

  def index
    @customers = Customer.all
  end

  def new
    @customer = Customer.new
    @specialists = Specialist.all
    # @consultation_matters = ConsultationMatter.all
    # @specialist = Specialist.find(params[:id])
    # add to fix property id problem 22/3/2-01
    @property = Property.find(params[:id])
    # ---

  end

  def create
    #@customer = Customer.new(customer_params)
    # @property = Property.last
     # add to fix property id problem 22/3/2-01
    @customer = Customer.new(name: customer_params['name'], mail: customer_params['mail'], specialist_id: customer_params['specialist_id'])
    @property = Property.find(customer_params['property_id'])
    # --- 22/3/2-01
    respond_to do |format|
      if @customer.save
         @property.customer_id = @customer.id
        ContactMailer.contact_mail(@customer).deliver

        format.html { redirect_to "/properties/new", notice: "Property was successfully created." }
        format.json { render :new, status: :created, location: @customer }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    @specialist = Specialist.find_by(id: @customer.specialist_id)
    @property = Property.find_by(customer_id: @customer.id)
    # @consultation_detail = Consultation_detail.find(params[:id])
  end

  private
  def set_customer
    @customer = Customer.find(params[:id])
  end

  def set_property
    # @property = Property.find(params[:id])
    @property = Property.last
  end

  def customer_params
    # params.require(:customer).permit( :name, :mail, :specialist_id)
    # add to fix property id problem 22/3/2-01
    params.require(:customer).permit( :name, :mail, :specialist_id, :property_id)
    # --- 22/3/2-01
  end
end

app/views/customers/_form.html.erb
<%= form_with(model: @customer, local: true ) do |form| %>

  <div class="green">
  <h3>オススメの専門家が5名見つかりました</h3>
  </div>

  <div class="specialist">
  <% @specialists.each do |specialist| %>
    <div class="chunk">
      <div class="icon"><p>アイコン</p><%= specialist.icon %></div>

      <div class="short">
        <div class="field">
          <p>氏名</p><%= specialist.name %>
        </div>

        <div class="field">
          <p>得意な物件</p><%= specialist.expertise_property %>
        </div>

        <div class="field">
          <p>相談可能項目</p><%= specialist.consultation_item %>
        </div>

        <div class="field">
          <p>資格</p><%= specialist.qualification %>
        </div>
      </div>

      <div class="long">
        <div class="field">
          <p>自己紹介</p><%= specialist.description %>
        </div>

        <div class="field">
          <p>経歴</p><%= specialist.career %>
        </div>
      </div>

      <div class="btn">
        <%= form.radio_button :specialist_id, specialist.id %>
        <%= specialist.id %>
        <%= link_to '相談を申し込む', class: "next" %>
      </div>
    </div>
  <% end %>


  <!-- <div class="specialist"> -->
    <%#= @specialist.name %>
    <%#= @specialist.expertise_property %>
    <%#= @specialist.consultation_item %>
    <%#= @specialist.qualification %>
    <%#= @specialist.description %>
    <%#= @specialist.career %>
    <%#= @specialist.icon %>
    <%#= @specialist.icon %>
    <%#= @specialist.id %>
  <!-- </div> -->


  <h3>専門家に相談するためお客様情報をご記入ください</h3>
  <%= form_with(model: @customer, local: true ) do |form| %>
    <div class="field">
      <%= form.label :氏名（必須）, class: "label" %>
      <%= form.text_field :name, class: "input", placeholder:"家野始真理" %>
    </div>

    <div class="field">
      <%= form.label :メールアドレス（必須）, class: "label" %>
      <%= form.text_field :mail, class: "input", placeholder:"◯◯◯◯@mail.com" %>
    </div>
  <% end %>

  <div class="message">
    <p>お客様のご相談内容に対して、</p>
    <p>専門家が24時間以内に</p>
    <p>登録したメールアドレス宛に</p>
    <p>回答をお送りします。</p>
  </div>

  <div class="privacy_policy">
    ㈱エンサポートのプライバシーポリシーは
    <%= link_to "こちら" %>
  </div>
  <%= form.hidden_field :property_id, value: @property.id %>
  <div class="btn">
    <%= form.submit "プライバシーポリシーに同意して専門家に相談内容を送る", class: "next" %>
  </div>

<% end %>

app/views/customers/index.html.erb
<h1>Customers#index</h1>
<p>Find me in app/views/customers/index.html.erb</p>

<table>
  <thead>
    <tr>
      <th>氏名</th>
      <th>メールアドレス</th>
    </tr>
  </thead>

  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.name %></td>
        <td><%= customer.mail %></td>
        <td><%= link_to '詳細', customer_path(customer.id) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/customers/new.html.erb
<%= render 'form', customer: @customer %>

app/views/customers/show.html.erb
<h1>Customers#show</h1>
<p>Find me in app/views/customers/show.html.erb</p>

<table>
  <tr>
    <th>氏名</th>
    <td><%= @customer.name %></td>
  </tr>
  <tr>
    <th>メールアドレス</th>
    <td><%= @customer.mail %></td>
  </tr>
  <tr>
    <th>担当の専門家</th>
    <td><%= @customer.specialist_id %></td>
    <td><%= @specialist.name %></td>
  </tr>
  <tr>
    <th>新築戸建</th>
    <td><%= @property.newly_built_house %></td>
  </tr>
  <tr>
    <th>中古戸建</th>
    <td><%= @property.used_house %></td>
  </tr>
  <tr>
    <th>新築マンション</th>
    <td><%= @property.newly_built_condominium %></td>
  </tr>
  <tr>
    <th>中古マンション</th>
    <td><%= @property.used_condominium %></td>
  </tr>
  <tr>
    <th>土地のみ</th>
    <td><%= @property.land %></td>
  </tr>
  <tr>
    <th>都道府県</th>
    <td><%= @property.prefecture_id %></td>
  </tr>
  <tr>
    <th>物件URL</th>
    <td><%= @property.url %></td>
  </tr>
  <tr>
    <th>物件名</th>
    <td><%= @property.name %></td>
  </tr>
  <tr>
    <th>その他</th>
    <td><%= @property.other %></td>
  </tr>
  <tr>
    <th>取扱会社</th>
    <td><%= @property.trader %></td>
  </tr>
  <tr>
    <th>販売価格</th>
    <td><%= @property.price %></td>
  </tr>
  <tr>
    <th>価格・返済</th>
    <td><%= @property.price_and_pepayment %></td>
    <td><%#= @consultation_detail.content %></td>
  </tr>
  <tr>
    <th>建物・構造</th>
    <td><%= @property.building_and_structure %></td>
  </tr>
  <tr>
    <th>間取り</th>
    <td><%= @property.floor_plan %></td>
  </tr>
  <tr>
    <th>周辺環境</th>
    <td><%= @property.surrounding_environment %></td>
  </tr>
  <tr>
    <th>家族・親族</th>
    <td><%= @property.family_relatives %></td>
  </tr>
  <tr>
    <th>その他の点</th>
    <td><%= @property.other_point %></td>
  </tr>

</table>